services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  DPX\ExporterBundle\:
    resource: '../../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests}'

  DPX\ExporterBundle\DataProvider\ExporterDataProvider:
    arguments:
      $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

  dpx.exporter.exporter_controller:
    class: DPX\ExporterBundle\Controller\ExporterController

  dpx.exporter.driver.xlsx:
    class: DPX\ExporterBundle\Driver\XlsxDriver