services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  DPX\ExporterBundle\:
    resource: '../../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests}'

  DPX\ExporterBundle\DataProvider\ExporterDataProvider:
    arguments:
      $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

  DPX\ExporterBundle\EventListener\KernelViewListener:
    tags:
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 17 }

  dpx.exporter.exporter_controller:
    class: DPX\ExporterBundle\Controller\ExporterController

  dpx.exporter.driver.xlsx:
    class: DPX\ExporterBundle\Driver\XlsxDriver

  dpx.exporter.driver.pdf:
    class: DPX\ExporterBundle\Driver\PdfDriver