services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  DIA\ExporterBundle\:
    resource: '../../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests}'

  DIA\ExporterBundle\DataProvider\ExporterDataProvider:
    arguments:
      $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection

  DIA\ExporterBundle\DoctrineExtension\ExporterExtension:
    arguments:
      $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection